spring:
  application:
    name: j-delivery-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 10
        order_updates: true
        order_inserts: true
        format_sql: true
        generate_statistics: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    baseline-version: 0
    schemas: postgres

server:
  port: 8086

notification:
  service:
    url:
      mail: ${NOTIFICATION_MAIL_URL}
    merchantLogin: ${NOTIFICATION_MERCHANT_LOGIN}
    merchantPassword: ${NOTIFICATION_MERCHANT_PASSWORD}
    id: ${NOTIFICATION_ID}
